### ISSUE TITLE
Compiling issue using Linux 

### ISSUE THREAD

**Issue by bshowket** [p-h-a-i-l/hoverboard-firmware-hack#1]
Compiling ending with no rule to make Target error as below.

Make: *** No rule to make Target 'build/hallinterrupts.o', needed by 'build/hover.elf' . Stop

**Comment by Giuliodori** [comment]
I also have the same problem that I can't solve.
The strange thing that I have the same problem with the bismont version.
With the Niklas version compiling without problem.

**Comment by p-h-a-i-l** [comment]
yeah, I (and btsimonh) both use platformio to build the code. I'll check If the Makefile can be fixed easily.

**Comment by Giuliodori** [comment]
Found the problem: in the makefile change "src / hallinterrupts.c" with src / hallInterrupts.c (capital I)

**Comment by p-h-a-i-l** [comment]
thanks @ombra80, fixed in 7def7804e4fb3f2ca095c9f34b3edcdd963ca029
