### ISSUE TITLE
reliable bidirectional communication :-)

### ISSUE THREAD

**Issue by RoboDurden** [p-h-a-i-l/hoverboard-firmware-hack#12]
I added a better checkCRC() to your main.c
```
bool checkCRC2(volatile Serialcommand* command) 
{
	uint8_t a[15];
	memcpy((void*)a,(void*)command,8);
	memcpy((void*)(a+8),(void*)command,7);
	
	for (uint8_t iOffset=0; iOffset< 8; iOffset++)
	{
		Serialcommand* pCmd = (Serialcommand*) (a+iOffset);
		uint32_t crc = 0;
		crc32((const void *)pCmd, 4, &crc); // 4 2x uint16_t = 4 bytes
		if(pCmd->crc == crc) 
		{
			memcpy((void*)command,(void*)pCmd,8);
			setScopeChannel(0, 1);
			if (	(abs(pCmd->steer)>1000) || (abs(pCmd->steer)>1000)	)
			{
				setScopeChannel(1,255);
				return false;
			}
			setScopeChannel(1,(int) iOffset);
			return true;
		}
	}
	setScopeChannel(0, 0);
	setScopeChannel(1, (int)command->crc);
	return false;
}
```

and i implemented a small feedback communication:
```
typedef struct{
   int16_t iSpeedL;		// 100* km/h
   int16_t iSpeedR;		// 100* km/h
   uint16_t iHallSkippedL;
   uint16_t iHallSkippedR;
   uint16_t iTemp;		// °C
   uint16_t iVolt;		// 100* V
   int16_t iAmpL;		// 100* A
   int16_t iAmpR;		// 100* A
   uint32_t crc;
} SerialFeedback;
volatile SerialFeedback oFeedback;

#ifdef DEBUG_SERIAL_USART3
#define UART_DMA_CHANNEL DMA1_Channel2
#endif
#ifdef DEBUG_SERIAL_USART2
#define UART_DMA_CHANNEL DMA1_Channel7
#endif

```
and
```
#if defined DEBUG_SERIAL_FEEDBACK && (defined DEBUG_SERIAL_USART2 || defined DEBUG_SERIAL_USART3)
	    if(UART_DMA_CHANNEL->CNDTR == 0) 
	    {
			oFeedback.iSpeedL	= (int) (float)HallData[0].HallSpeed_mm_per_s * 0.36f;
			oFeedback.iSpeedR	= (int) (float)HallData[1].HallSpeed_mm_per_s * 0.36f;
			oFeedback.iHallSkippedL	= HallData[0].HallSkipped;
			oFeedback.iHallSkippedR	= HallData[1].HallSkipped;
			oFeedback.iTemp	= (int)	board_temp_deg_c;
			oFeedback.iVolt	= (int)	(batteryVoltage * 100.0f);
			oFeedback.iAmpL = (int) (currentL * 100.0f);
			oFeedback.iAmpR = (int)	(currentR * 100.0f);
			oFeedback.crc = 0;
			crc32((const void *)&oFeedback, sizeof(oFeedback)-4, &oFeedback.crc);

			UART_DMA_CHANNEL->CCR &= ~DMA_CCR_EN;
			UART_DMA_CHANNEL->CNDTR = sizeof(oFeedback);
			UART_DMA_CHANNEL->CMAR  = (uint32_t)&oFeedback;
			UART_DMA_CHANNEL->CCR |= DMA_CCR_EN;
	    }
#else
//ROBO end

      // ####### DEBUG SERIAL OUT #######
      #ifdef CONTROL_ADC
        setScopeChannel(0, (int)adc_buffer.l_tx2);  // 1: ADC1
        setScopeChannel(1, (int)adc_buffer.l_rx2);  // 2: ADC2
      #endif
      setScopeChannel(2, (int)speedR);  // 3: output speed: 0-1000
      setScopeChannel(3, (int)speedL);  // 4: output speed: 0-1000
      setScopeChannel(4, (int)adc_buffer.batt1);  // 5: for battery voltage calibration
      setScopeChannel(5, (int)(batteryVoltage * 100.0f));  // 6: for verifying battery voltage calibration
      setScopeChannel(6, (int)board_temp_adc_filtered);  // 7: for board temperature calibration
      setScopeChannel(7, (int)board_temp_deg_c);  // 8: for verifying board temperature calibration
      consoleScope();
#endif	//ROBO
```

changes in bldc.c
```
float batteryVoltage = BAT_NUMBER_OF_CELLS * 4.0;
float currentL = 0;	//ROBO
float currentR = 0;	//ROBO
```
and
```
  currentL = MOTOR_AMP_CONV_DC_AMP * (float) (adc_buffer.dcl - offsetdcl);	//ROBO
  currentR = MOTOR_AMP_CONV_DC_AMP * (float) (adc_buffer.dcr - offsetdcr);	//ROBO
  
  if(ABS((adc_buffer.dcl - offsetdcl) * MOTOR_AMP_CONV_DC_AMP) > DC_CUR_LIMIT || timeout > TIMEOUT || enable == 0) {
``` 

would be nice if you add this to your repo. Your old `checkCRC` isn't really of any use ?

Don't really know how to contribute myself.

And i rather wish to continue with the c++ port

here the modified firmware in action: https://youtu.be/5Wq42cbGRSU

the Roland :-)

**Comment by p-h-a-i-l** [comment]
Hello Roland,
thanks, this would have been very helpful to me one year ago ;)

Unfortunately I also have a different focus right now, working on the bipropellant fork. This is kind of a dead end for me.
If I would add this to my repo, it would take me around a day of work. First going through it, figuring out how to merge manually and then writing a program for the other side to test with.
You can make a fork of this repo here and push your tested code If you like. If you need some help with git and github I can try to give you some pointers. (Auch auf Deutsch wenn das einfacher ist.)

best regards
phail

**Comment by RoboDurden** [comment]
First rule: you always speak yes..

> Unfortunately I also have a different focus right now, working on the bipropellant fork. This is kind of a dead end for me.

What if life would not only be about you ?

The NiklasFauth-Original was never really tested for uart-control and does not work.
Your bipropellant fork is about a one-binary-for-all and will not be for people to add their needs.

My adds to bldc.c obviously do no harm and you can add them without testing.
Replacing your useless checkCRC with my version will only take you 60 seconds, then select your code on my https://pionierland.de/hoverhack , hit compile and you know everything is okay.

(memcpy() needs `#include <string.h>` )

And when people wish to add their own back-communication they can still use your fork by editing the config.h and main.c on my online compiler.

Second rule: ...

**Comment by p-h-a-i-l** [comment]
> First rule: you always speak yes..

> Second rule: ...

?

> > Unfortunately I also have a different focus right now, working on the bipropellant fork. This is kind of a dead end for me.
> 
> What if life would not only be about you ?

Excuse me? You are writing this in a repo where I put in a lot of work for others. Now you want me to do the housekeeping for your fun project. This is quite offensive to me.

> The NiklasFauth-Original was never really tested for uart-control and does not work.
> Your bipropellant fork is about a one-binary-for-all and will not be for people to add their needs.

The bipropellant fork is more open to changes then the original fork. Look at the commit histories, Niklas' repo is stale for over a year now. No pull requests are considered.

> My adds to bldc.c obviously do no harm and you can add them without testing.
> Replacing your useless checkCRC with my version will only take you 60 seconds, then select your code on my https://pionierland.de/hoverhack , hit compile and you know everything is okay.

I don't know that for sure, too hacky for me to copy paste code snippets from postings into the source. I already wrote my time estimation above. Maybe I'm too slow. Compiling is no issue, the toolchain is really easy to setup locally.


If you really want to make contributions to projects on **git**hub, I don't see a way other then using git.
