### ISSUE TITLE
Actual speed reading

### ISSUE THREAD

**Issue by Giuliodori** [p-h-a-i-l/hoverboard-firmware-hack#2]
Is there a simple example to read the current speed with SERIAL_USART2_IT?
the example for the Serial Command works great, but
I need to always read the real speed with my teensy.
I believe it is possible but I am a beginner and I have many difficulties
Thanks in advance.

**Comment by p-h-a-i-l** [comment]
Sorry, no simple example. You can look at my implementation and try to adapt, but it is not too easy to read.
I basically took the existing code from the hoverboard fw and use it to parse incoming messages. Didn't wan't to invent the wheel twice. The code is work in progress, but I pushed a newer version so you can have a look at the hall sensor data request and processing.
https://github.com/p-h-a-i-l/hoverboard-control/blob/8ec28ef75cd44781d6d37ce81bbe23bee9ac40bf/src/output.cpp#L108-L124
