### ISSUE TITLE
Reading back speeds kills the set point

### ISSUE THREAD

**Issue by kervinck** [p-h-a-i-l/hoverboard-firmware-hack#3]
Fyi, I found that reading back speeds, in my case using the 0x07 command, interferes with the FILTER mechanism of main.c. This effectively prevents main.c from reaching the required final set point in case one reads back the speed before it has settled.

The problem is in the function PreRead_getspeeds: it overwrites the desired setpoints with the current speed/steer, which might still be developing.

```
void PreRead_getspeeds(void){
    speedsx.speedl = SpeedData.wanted_speed_mm_per_sec[0];
    speedsx.speedr = SpeedData.wanted_speed_mm_per_sec[1];
    PwmSteerCmd.base_pwm = speed; # <--- this is also the set point!
    PwmSteerCmd.steer = steer;    # <--- this is also the set point!
}

```

Introduced here https://github.com/p-h-a-i-l/hoverboard-firmware-hack/commit/27ef84bc9188ba5f17a257685efe3e939b9b0405

P.S: My workaround is:

`#define FILTER 1.0
`

**Comment by p-h-a-i-l** [comment]
That's right, this does some strange things. 

You need to watch out, "speed" is used in a wrong way here. Speed is just the set point for PWM (speed/steer from the original firmware is also just pwm..)

If you want to read the actual speed, use 0x02 HallData. I'll push a complete new protocol version in the next days, the set point is already changed to PWM Data in there.

**Comment by kervinck** [comment]
Oh don't worry, I'm fine in hacking the firmware in anyway I like. I just wanted to report this behaviour I suspect is unintended. The fork is great. (BTW, there is a dummy byte transmitted between the payload and the checksum for every request message.)
