### ISSUE TITLE
Lots of noise on serial line

### ISSUE THREAD

**Issue by Giuliodori** [p-h-a-i-l/hoverboard-firmware-hack#7]
The firmware works well, but often I' have problems with serial transmission:
when the motor is active (even at zero speed) I see many distortions with the oscilloscope and the motor stops.
I have tried with short cables, shielded cables, ferrite, etc. but the noise don't stop.
My  Teensy 3.2 (3.3v) is powered with an external battery with the common ground.
Some advice?
Of course with the analog command works well and i've tried with different boudrate.

Thanks in advance.

![20190516_222911](https://user-images.githubusercontent.com/48888556/57971187-06064500-798b-11e9-8d8c-849f842eac56.jpg)
![20190516_222921](https://user-images.githubusercontent.com/48888556/57971188-06064500-798b-11e9-8047-4af5dbce8510.jpg)

**Comment by p-h-a-i-l** [comment]
That's what I'm also seeing, it's my biggest problem right now with the serial connection. 
Where did you attach the shielded cables? Did you replace the Sensor cables on the board, or did you plug them in?
However, it must be possible to get the system robust enough without hardware changes, in the original hoverboard configuration the Sensor cable is unshielded and parallel to the motor wires, too.

If you try more things, please keep me updated :)

**Comment by Giuliodori** [comment]
For the shielding I wrapped a steel sock around the original cables, but it did not improve the noise.
I believe that there is something in the firmware that makes the serial buzz, because when the wheels are stationary there should be no noise.

I would like to try with an optoisolator but I don't think changes, because the disturbance comes from the motherboard.

![20190518_135744](https://user-images.githubusercontent.com/48888556/57971846-e58eb880-7993-11e9-903e-d7e891613dbb.jpg)

**Comment by p-h-a-i-l** [comment]
> For the shielding I wrapped a steel sock around the original cables, but it did not improve the noise.
> I believe that there is something in the firmware that makes the serial buzz, because when the wheels are stationary there should be no noise.

When the wheels are stationary, there is still current to the motor. If you set enable = 0, no current is flowing.

**Comment by p-h-a-i-l** [comment]
From the picture it looks like you put a ferrite and shield on RX and TX, but not in GND. Did you try to include GND?

**Comment by Giuliodori** [comment]
With enable = 0 is the second graph . I wanted to say that if I have pwml = 0 and pwmr = 0 I shouldn't hear the buzz.
with the shielding I have not tried all the possible combinations, but I will try.


in the link the result until now.
[https://youtu.be/8yrex-ifpPg](url)

**Comment by p-h-a-i-l** [comment]
And I thought I've seen all the crazy things you could motorize :) well done

What kind of radio are you using for RC?
